/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductWebhooksRouteImport } from './routes/product/webhooks'
import { Route as ProductTemplateBuilderRouteImport } from './routes/product/template-builder'
import { Route as ProductSmtpApiRouteImport } from './routes/product/smtp-api'
import { Route as ProductRestApiRouteImport } from './routes/product/rest-api'
import { Route as ProductDomainAuthRouteImport } from './routes/product/domain-auth'
import { Route as ProductAnalyticsRouteImport } from './routes/product/analytics'
import { Route as GuidesIpWarmingRouteImport } from './routes/guides/ip-warming'
import { Route as GuidesEmailAuthenticationRouteImport } from './routes/guides/email-authentication'
import { Route as GuidesAvoidingSpamRouteImport } from './routes/guides/avoiding-spam'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs/troubleshooting'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductWebhooksRoute = ProductWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => ProductRoute,
} as any)
const ProductTemplateBuilderRoute = ProductTemplateBuilderRouteImport.update({
  id: '/template-builder',
  path: '/template-builder',
  getParentRoute: () => ProductRoute,
} as any)
const ProductSmtpApiRoute = ProductSmtpApiRouteImport.update({
  id: '/smtp-api',
  path: '/smtp-api',
  getParentRoute: () => ProductRoute,
} as any)
const ProductRestApiRoute = ProductRestApiRouteImport.update({
  id: '/rest-api',
  path: '/rest-api',
  getParentRoute: () => ProductRoute,
} as any)
const ProductDomainAuthRoute = ProductDomainAuthRouteImport.update({
  id: '/domain-auth',
  path: '/domain-auth',
  getParentRoute: () => ProductRoute,
} as any)
const ProductAnalyticsRoute = ProductAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProductRoute,
} as any)
const GuidesIpWarmingRoute = GuidesIpWarmingRouteImport.update({
  id: '/guides/ip-warming',
  path: '/guides/ip-warming',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesEmailAuthenticationRoute =
  GuidesEmailAuthenticationRouteImport.update({
    id: '/guides/email-authentication',
    path: '/guides/email-authentication',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesAvoidingSpamRoute = GuidesAvoidingSpamRouteImport.update({
  id: '/guides/avoiding-spam',
  path: '/guides/avoiding-spam',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRouteWithChildren
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/tutorials': typeof TutorialsRoute
  '/use-cases': typeof UseCasesRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/guides/avoiding-spam': typeof GuidesAvoidingSpamRoute
  '/guides/email-authentication': typeof GuidesEmailAuthenticationRoute
  '/guides/ip-warming': typeof GuidesIpWarmingRoute
  '/product/analytics': typeof ProductAnalyticsRoute
  '/product/domain-auth': typeof ProductDomainAuthRoute
  '/product/rest-api': typeof ProductRestApiRoute
  '/product/smtp-api': typeof ProductSmtpApiRoute
  '/product/template-builder': typeof ProductTemplateBuilderRoute
  '/product/webhooks': typeof ProductWebhooksRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRouteWithChildren
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/tutorials': typeof TutorialsRoute
  '/use-cases': typeof UseCasesRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/guides/avoiding-spam': typeof GuidesAvoidingSpamRoute
  '/guides/email-authentication': typeof GuidesEmailAuthenticationRoute
  '/guides/ip-warming': typeof GuidesIpWarmingRoute
  '/product/analytics': typeof ProductAnalyticsRoute
  '/product/domain-auth': typeof ProductDomainAuthRoute
  '/product/rest-api': typeof ProductRestApiRoute
  '/product/smtp-api': typeof ProductSmtpApiRoute
  '/product/template-builder': typeof ProductTemplateBuilderRoute
  '/product/webhooks': typeof ProductWebhooksRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRouteWithChildren
  '/security': typeof SecurityRoute
  '/status': typeof StatusRoute
  '/tutorials': typeof TutorialsRoute
  '/use-cases': typeof UseCasesRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/guides/avoiding-spam': typeof GuidesAvoidingSpamRoute
  '/guides/email-authentication': typeof GuidesEmailAuthenticationRoute
  '/guides/ip-warming': typeof GuidesIpWarmingRoute
  '/product/analytics': typeof ProductAnalyticsRoute
  '/product/domain-auth': typeof ProductDomainAuthRoute
  '/product/rest-api': typeof ProductRestApiRoute
  '/product/smtp-api': typeof ProductSmtpApiRoute
  '/product/template-builder': typeof ProductTemplateBuilderRoute
  '/product/webhooks': typeof ProductWebhooksRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/product'
    | '/security'
    | '/status'
    | '/tutorials'
    | '/use-cases'
    | '/docs/troubleshooting'
    | '/guides/avoiding-spam'
    | '/guides/email-authentication'
    | '/guides/ip-warming'
    | '/product/analytics'
    | '/product/domain-auth'
    | '/product/rest-api'
    | '/product/smtp-api'
    | '/product/template-builder'
    | '/product/webhooks'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/product'
    | '/security'
    | '/status'
    | '/tutorials'
    | '/use-cases'
    | '/docs/troubleshooting'
    | '/guides/avoiding-spam'
    | '/guides/email-authentication'
    | '/guides/ip-warming'
    | '/product/analytics'
    | '/product/domain-auth'
    | '/product/rest-api'
    | '/product/smtp-api'
    | '/product/template-builder'
    | '/product/webhooks'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/product'
    | '/security'
    | '/status'
    | '/tutorials'
    | '/use-cases'
    | '/docs/troubleshooting'
    | '/guides/avoiding-spam'
    | '/guides/email-authentication'
    | '/guides/ip-warming'
    | '/product/analytics'
    | '/product/domain-auth'
    | '/product/rest-api'
    | '/product/smtp-api'
    | '/product/template-builder'
    | '/product/webhooks'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  StatusRoute: typeof StatusRoute
  TutorialsRoute: typeof TutorialsRoute
  UseCasesRoute: typeof UseCasesRoute
  GuidesAvoidingSpamRoute: typeof GuidesAvoidingSpamRoute
  GuidesEmailAuthenticationRoute: typeof GuidesEmailAuthenticationRoute
  GuidesIpWarmingRoute: typeof GuidesIpWarmingRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/webhooks': {
      id: '/product/webhooks'
      path: '/webhooks'
      fullPath: '/product/webhooks'
      preLoaderRoute: typeof ProductWebhooksRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/template-builder': {
      id: '/product/template-builder'
      path: '/template-builder'
      fullPath: '/product/template-builder'
      preLoaderRoute: typeof ProductTemplateBuilderRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/smtp-api': {
      id: '/product/smtp-api'
      path: '/smtp-api'
      fullPath: '/product/smtp-api'
      preLoaderRoute: typeof ProductSmtpApiRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/rest-api': {
      id: '/product/rest-api'
      path: '/rest-api'
      fullPath: '/product/rest-api'
      preLoaderRoute: typeof ProductRestApiRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/domain-auth': {
      id: '/product/domain-auth'
      path: '/domain-auth'
      fullPath: '/product/domain-auth'
      preLoaderRoute: typeof ProductDomainAuthRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/analytics': {
      id: '/product/analytics'
      path: '/analytics'
      fullPath: '/product/analytics'
      preLoaderRoute: typeof ProductAnalyticsRouteImport
      parentRoute: typeof ProductRoute
    }
    '/guides/ip-warming': {
      id: '/guides/ip-warming'
      path: '/guides/ip-warming'
      fullPath: '/guides/ip-warming'
      preLoaderRoute: typeof GuidesIpWarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/email-authentication': {
      id: '/guides/email-authentication'
      path: '/guides/email-authentication'
      fullPath: '/guides/email-authentication'
      preLoaderRoute: typeof GuidesEmailAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/avoiding-spam': {
      id: '/guides/avoiding-spam'
      path: '/guides/avoiding-spam'
      fullPath: '/guides/avoiding-spam'
      preLoaderRoute: typeof GuidesAvoidingSpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ProductRouteChildren {
  ProductAnalyticsRoute: typeof ProductAnalyticsRoute
  ProductDomainAuthRoute: typeof ProductDomainAuthRoute
  ProductRestApiRoute: typeof ProductRestApiRoute
  ProductSmtpApiRoute: typeof ProductSmtpApiRoute
  ProductTemplateBuilderRoute: typeof ProductTemplateBuilderRoute
  ProductWebhooksRoute: typeof ProductWebhooksRoute
}

const ProductRouteChildren: ProductRouteChildren = {
  ProductAnalyticsRoute: ProductAnalyticsRoute,
  ProductDomainAuthRoute: ProductDomainAuthRoute,
  ProductRestApiRoute: ProductRestApiRoute,
  ProductSmtpApiRoute: ProductSmtpApiRoute,
  ProductTemplateBuilderRoute: ProductTemplateBuilderRoute,
  ProductWebhooksRoute: ProductWebhooksRoute,
}

const ProductRouteWithChildren =
  ProductRoute._addFileChildren(ProductRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRouteWithChildren,
  SecurityRoute: SecurityRoute,
  StatusRoute: StatusRoute,
  TutorialsRoute: TutorialsRoute,
  UseCasesRoute: UseCasesRoute,
  GuidesAvoidingSpamRoute: GuidesAvoidingSpamRoute,
  GuidesEmailAuthenticationRoute: GuidesEmailAuthenticationRoute,
  GuidesIpWarmingRoute: GuidesIpWarmingRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
